### ISSUE TITLE
Dewdrop 17900 error

### ISSUE THREAD

**Issue by shikulja** [laytya/FuBar_PursueFu#1]
<img width="333" alt="image" src="https://user-images.githubusercontent.com/3386359/200633184-58fdc7c1-a780-48b1-8906-87de9cbd06f9.png">

(Possibly in combination with pfquest)

**Comment by laytya** [comment]
У меня библа 17889 - скинь что там за 17900...

**Comment by shikulja** [comment]
@laytya 
[Dewdrop-2.0 17900.zip](https://github.com/laytya/FuBar_PursueFu/files/9969242/Dewdrop-2.0.17900.zip)

**Comment by laytya** [comment]
это ты для ру локали не пашет? ты неправильно там сделал.

**Comment by shikulja** [comment]
@laytya Dewdrop я использовал внешний. В коде не лазил (кроме BS и заголовков), всё как было изначально

**Comment by laytya** [comment]
Забирай https://github.com/laytya/FuBar_PursueFu/commit/a55a8d52fd541e6d47c1a7e1b15acbee3283924f

**Comment by shikulja** [comment]
@laytya Вроде бы работает.
Обращал внимание на строки команд, но почему-то решил их не добавлять.

**Comment by laytya** [comment]
Это просто описание - народ знает про эти команды - чтоб понятно было о чем это
